export const template = {
  getMessage() {
    let message = '\n'
    message += '<div class="box">\n'
    message += ' <h1 class="meg">说明</h1>\n'
    message += ' <div class="book">\n'
    message += ' <p>书　名：[[TITLE]] [[SEQUENCE]]</p>\n'
    message += ' <p>图　文：[[AUTHOR]]</p>\n'
    message += ' <p>制　作：[[MAKER]]</p>\n'
    message += ' </div>\n'
    message += ' <div class="option">\n'
    message
      += ' <p>声　明：此EPUB文档由软件自动生成，仅供测试，禁止传播和商用。</p>\n'
    message
      += ' <p>地　址：<a href="https://taiyuuki.github.io/elepub-web-build/"><span style="color:#fff">https://taiyuuki.github.io/elepub-web-build/</span></a></p>\n'
    message
      += ' <p>阅读器：请使用<a href="http://www.duokan.com/product"><span style="color:#fff">多看阅读</span></a>，并将翻页模式设置为“上下翻页”。</p>\n'
    message += ' </div>\n'
    message += ' </div>\n'
    return message
  },
  getCss() {
    let css = '\n'
    css += 'body {\n'
    css += ' padding: 0;\n'
    css += ' margin: 0;\n'
    css += ' text-indent: 0;\n'
    css += ' duokan-text-indent: 0;\n'
    css += '}\n'
    css += 'p {\n'
    css += ' text-indent: 0;\n'
    css += ' duokan-text-indent: 0;\n'
    css += ' display: block;\n'
    css += ' line-height: 1.3em;\n'
    css += ' margin-top: 0.6em;\n'
    css += ' margin-bottom: 0.6em;\n'
    css += '}\n'
    css += 'div {\n'
    css += ' text-indent: 0;\n'
    css += ' duokan-text-indent: 0;\n'
    css += ' margin: 0;\n'
    css += ' padding: 0;\n'
    css += ' text-align: justify;\n'
    css += '}\n'
    css += 'img {\n'
    css += ' width: 100%;\n'
    css += '}\n'
    css += 'a {\n'
    css += ' text-decoration: none;\n'
    css += '}\n'
    css += 'a:hover {\n'
    css += ' background-color: rgba(0, 0, 0, 0.5);\n'
    css += '}\n'
    css += '.box {\n'
    css += ' color: #258;\n'
    css += ' padding: 5px;\n'
    css += ' margin: 10% -0.25em;\n'
    css += ' border: 1px solid #258;\n'
    css += ' background-color: rgba(34, 85, 136, 0.1);\n'
    css += '}\n'
    css += '.box p {\n'
    css += ' font-size: 0.8em;\n'
    css += '}\n'
    css += '.book {\n'
    css += ' font-family: "微软雅黑", "黑体", "ht", "sans-serif";\n'
    css += '}\n'
    css += '.book p {\n'
    css += ' font-size: 1em;\n'
    css += ' text-shadow: 1px 1px 1px #fff;\n'
    css += ' text-indent: 0;\n'
    css += ' duokan-text-indent: 0;\n'
    css += '}\n'
    css += '.meg {\n'
    css += ' margin: -5px;\n'
    css += ' padding: 5px;\n'
    css += ' color: #fff;\n'
    css += ' font-family: "gy", "DK-FANGSONG", "fs", "fangsong", "仿宋";\n'
    css += ' font-weight: bold;\n'
    css += ' font-size: 1.2em;\n'
    css += ' text-indent: 0;\n'
    css += ' duokan-text-indent: 0;\n'
    css += ' text-align: center;\n'
    css += ' line-height: 120%;\n'
    css += ' background-color: #258;\n'
    css += '}\n'
    css += '.option {\n'
    css += ' font-family: "gy", "DK-FANGSONG", "fs", "fangsong", "仿宋";\n'
    css += ' font-size: 1em;\n'
    css += ' font-weight: bold;\n'
    css += ' margin: -5px;\n'
    css += ' padding: 5px;\n'
    css += ' line-height: 120%;\n'
    css += ' background-color: rgba(34, 85, 136, 0.8);\n'
    css += ' color: #fff;\n'
    css += '}\n'
    css += '.option p {\n'
    css += ' text-indent: -4em;\n'
    css += ' duokan-text-indent: -4em;\n'
    css += ' padding-left: 4em;\n'
    css += '}\n'

    return css
  },

  getDuokanExtension() {
    let extension = '\n'
    extension += '<?xml version="1.0" encoding="UTF-8"?>\n'
    extension += '<duokan-extension version="2.4.0">\n'
    extension += '  <display-options layout="vertical-comic"/>\n'
    extension += '  <writing-options>\n'
    extension += '    <option name="writing-mode">horizontal-tb</option>\n'
    extension += '    <option name="direction">ltr</option>\n'
    extension += '  </writing-options>\n'
    extension += '</duokan-extension>\n'
    return extension
  },
}